disabled = false
languageCode = "zh-TW"
languageName = "繁體中文"
weight = 1
title = "Henry Yang 亨利羊"

[params]
  displayName = "繁中"
  isoCode = "zh-TW"
  rtl = false
  dateFormat = "2006年1月2日"

[params.author]
  name = "Henry Yang 亨利羊"
