# -- Theme Options --
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = false
enableCodeCopy = false

[header]
  layout = "basic"

[footer]
  showMenu = false
  showCopyright = false
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = false

[homepage]
  layout = "profile"
  showRecent = false

[article]
  showDate = false
  showAuthor = false
  showBreadcrumbs = false
  showPagination = false
  showReadingTime = false
  showTableOfContents = false
  showTaxonomies = false
  showWordCount = false

[list]
  showBreadcrumbs = false
  showSummary = false
  showTableOfContents = false

[taxonomy]
  showTermCount = false
  showBreadcrumbs = false
