# -- Theme Options --
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "ocean"  # 可選：blowfish, avocado, fire, ocean, forest, princess, neon, bloody, terminal, marvel, noir, autumn, congo, slate
defaultAppearance = "light"  # light 或 dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

disableImageOptimization = false

[header]
  layout = "fixed"  # basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"  # page, profile, hero, card, background, custom
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = false
  cardViewScreenWidth = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = true
  showAuthor = true
  showHero = true
  heroStyle = "basic"  # basic, big, background, thumbAndBackground
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showZenMode = false
  sharingLinks = ["facebook", "twitter", "linkedin", "email", "line"]

[list]
  showHero = false
  showBreadcrumbs = true
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = true
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false

[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = true
  cardView = true

[term]
  showHero = false
  showBreadcrumbs = true
  showTableOfContents = true
  groupByYear = false
  cardView = true
