# -- Theme Options --
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

# 背景圖片（之後可替換為你自己的圖片）
# defaultBackgroundImage = "/img/background.jpg"

[header]
  layout = "fixed-fill-blur"  # 頂部模糊玻璃效果

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"  # 動態背景模式
  layoutBackgroundBlur = true  # 滾動時背景模糊效果
  homepageImage = "/img/home-background.jpg"  # 首頁背景圖
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/blog/"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showHero = true
  heroStyle = "background"  # 背景英雄模式
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showZenMode = true
  sharingLinks = ["facebook", "twitter", "linkedin", "email", "line"]

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = true
  cardView = true

[term]
  showHero = false
  showBreadcrumbs = true
  showTableOfContents = false
  groupByYear = false
  cardView = true
